# Generated by Django 5.1.4 on 2025-01-23 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000000)),
                ('Dates', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
